version: '3.7'

networks:
  pug-previewer-network:
    name: pug-previewer-network
    driver: bridge

services:
  application:
    container_name: pug-previewer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 18
        USER_UID: 1000
        USER_GID: 1000
    networks:
      - pug-previewer-network
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    user: node
    env_file:
      - ./workspace.env
    ports:
      - 3000:3000